languageCode: "en-us"
title: "CoZ:City of Zion"
baseURL: "https://cityofzion.io/"
pygmentsStyle: "monokai"
pygmentsUseClasses: true
MetaDataFormat: "yaml"
permalinks:
  post: /:year/:month/:title/

params:
  github: CityOfZion
  twitter: coz_official
  googleAnalyticsUserID: "UA-XXX"
