languageCode: "en-us"
baseURL: "https://cityofzion.io/"
pygmentsStyle: "monokai"
pygmentsUseClasses: true
MetaDataFormat: "yaml"
title: "CoZ:City of Zion"

permalinks:
  post: /:year/:month/:title/

params:
  github: "CityOfZion"
  twitter: "coz_official"
  reddit: "NEO"
  discord: "R8v48YA"
  facebook: "CityOfZionOfficial"
  medium: "@cityofzion"
  googleAnalyticsUserID: "UA-XXX"

  image: "opengraph-home.jpg"
  description: "City of Zion is a global, independent group of open source developers, designers and translators which support the NEO core and ecosystem."